# CAFE required metadata changes

rename:
  precip: pr
  t_ref_max: tasmax
  u_ref: uas
  v_ref: vas
  rh: hur

drop_coords:
  - average_DT
  - average_T1
  - average_T2
  - zsurf
  - area

round_coords:
  - lat

